language: java
notifications:
  webhooks:
    urls:
      - http://176.34.150.89/payload/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
